import 'package:flutter/material.dart';

class ChinaFood with ChangeNotifier {
  final String id;
  final String title;
  final String country;
  final String imageUrl;
  final double codeFood;
  final List<String> ingredients;
  final List<String> steps;
  final String duration;
  final String information;
  bool isFavorite;

  ChinaFood({
    @required this.id,
    @required this.title,
    @required this.country,
    @required this.imageUrl,
    @required this.codeFood,
    @required this.ingredients,
    @required this.steps,
    @required this.duration,
    @required this.information,
  });
}

class China with ChangeNotifier {
  List<ChinaFood> _chinaRecipes = [
    ChinaFood(
        id: 'r1',
        title: 'Dim Sums',
        country: 'China',
        imageUrl:
            'https://i.ndtvimg.com/i/2015-10/dimsum_625x350_51446202982.jpg',
        codeFood: 3,
        information:
            'One of the most loves street food from the north east, widely popular across northern India now comes to your kitchen! Small bite-sized rounds stuffed with veggies or meat. Dimsums are perfect steamed snack to delight those evening cravings.',
        duration: '1 hr 20 mins',
        ingredients: [
          'For chicken and prawn dumplings:  ',
          '150 gms chicken                   ',
          '150 gms prawn                     ',
          '5 gms sugar                       ',
          '5 ml sesame oil                   ',
          '2.5 gms white pepper              ',
          'Wonton skin                       ',
          'Potato starch                     ',
          'Salt                              ',
          'For vegetable coriander dumplings:',
          '10 gms carrots                    ',
          '10 gms button mushrooms           ',
          '10 gms water chestnuts            ',
          '10 gms bamboo shoots              ',
          '10 gms garlic                     ',
          '10 ml oil                         ',
          '10 gms brown garlic               ',
          '5 gms sugar                       ',
          '5 gms sesame oil                  ',
          'For wonton skin:                  ',
          'Potato starch                     ',
          'Salt                              ',
          '50 gms wheat starch               ',
        ],
        steps: [
          'Mince chicken and prawns and mix with sugar, salt, sesame oil and potato starch. Stuff the mixture in the wanton skin and steam.',
          'Serve with Diamond & soya Sauce                                                                                                 ',
          'Mix all ingredients except for wanton skin. Stuff the mixture in the wanton skin and steam.                                     ',
          'Serve with diamond sauce.                                                                                                       ',
          'Add cold water with potato and 50 gm of wheat starch, and mix with a pinch of salt.                                             ',
          'Add hot water to the mixture and stir till it thickens. Add potato starch till it gets tight.                                   ',
          'Make a roll and cut into small balls adding wheat starch over the ball.                                                         ',
          'Then roll the balls in a flat and round shape with a roller and add fillings.                                                   ',
          'Soak 250 gm red chilies for 3 hours. Make into paste. Fry 100 gm garlic in oil.                                                 ',
          'When garlic gets brown, add chili paste, salt, sugar and soya bean powder.                                                      ',
        ]),
    ChinaFood(
        id: 'r1',
        title: 'Hot & Sour Soup',
        country: 'China',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-06/soup-625_625x350_81466064298.jpg',
        codeFood: 4,
        information:
            'Isn\'t it great to warm up with a piping hot bowl of soup during the winters? Here is a soup with a spicy and sour broth. It is made with the goodness of mushrooms, cabbage, carrot and a spicy twist of red peppers or white pepper and sour with vinegar.',
        duration: '1 hr 15 mins',
        ingredients: [
          '5 gms carrot          ',
          '5 gms cabbage         ',
          '5 gms black mushrooms ',
          '5 gms button mushrooms',
          '5 gms bamboo shoots   ',
          '5 gms bean sprouts    ',
          '5 gms fresh beans     ',
          '100 gms chicken       ',
          '60 gms prawns         ',
          '1 tbsp soya sauce     ',
          '1/2 tbsp chili powder ',
          '1/2 tsp white pepper  ',
          '2 tbsp corn flour     ',
          '1 Egg                 ',
          '1 tbsp coriander      ',
          '1 tsp chili oil       ',
          '2 cups stock          ',
          '1 1/2 tbsp vinegar    ',
          'to taste salt         ',
        ],
        steps: [
          'Cut all vegetables, chicken and prawns in julienne style.',
          'Take a wok and add the stock and add all vegetables along with chicken and cook.',
          'Later add pepper, soy, salt, coriander, chili oil and vinegar.',
          'Add corn flour for thickness and lastly the egg.',
        ]),
    ChinaFood(
        id: 'r1',
        title: 'Quick Noodles',
        country: 'China',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-06/noodles-625_625x350_41466064269.jpg',
        codeFood: 5,
        information:
            'One of the staples in every home, noodles are not just a kid\'s favourite snack to binge on but are also equally loved by adults. Here is a noodles recipe that is super quick and easy to prepare at home. Just bung in all your favourite veggies and create a masterpiece of your own.',
        duration: '45 min',
        ingredients: [
          '2 packets noodles                   ',
          '1 tbsp vegetable oil                ',
          '1 cup onion, sliced                 ',
          '1 cup pepper, sliced                ',
          '1 cup carrot, julienne              ',
          '1 cup spring onions , sliced        ',
          '1 cup mushrooms, sliced             ',
          '1/2 Iceberg/romaine lettuce         ',
          '1 tbsp ginger & garlic chilli paste ',
          '1 tbsp soy sauce                    ',
          '1 tbsp schezwan sauce               ',
          '1/2 tsp turmeric powder             ',
          '1 tsp sugar                         ',
          '1 tbsp coriander, chopped           ',
          '1 tbsp lemon juice                  ',
          '1 tsp vinegar                       ',
        ],
        steps: [
          'Cook the noodles in boiling water according to the instructions depending upon the kind of noodles you are using.',
          ' Drain, cool under running water.',
          'Add a few drops of oil to the noodles to prevent them from sticking to each other.      ',
          'In a wok, heat some oil to almost smoking point.      ',
          'Then add the sliced onions, peppers, carrots, spring onions and mushrooms and the ginger garlic chilli paste.',
          'Mix the soy, schezwan, turmeric and the sugar in a small bowl and mix well.',
          'Add this mix to the vegetables. Then add the noodles and toss well. Season to taste.',
          'Finish with chopped coriander and toasted crushed peanuts and lemon juice.',
        ]),
    ChinaFood(
        id: 'r1',
        title: 'Szechwan Chicken',
        country: 'China',
        imageUrl:
            'https://i.ndtvimg.com/i/2015-02/chilli-chicken_625x350_81424323578.jpg',
        codeFood: 4,
        information:
            'A fiery delight straight from the Sichuan region. It is loaded with pungent spices like brown pepper. red chillies, ginger, green chillies and white pepper.',
        duration: '45 min',
        ingredients: [
          '2-3 spring onions, chopped               ',
          '5-6 dry red chillies (deseeded), chopped ',
          '2-3 tbsp ginger, chopped                     ',
          '3 tbsp brown pepper corn                     ',
          '3 tbsp green pepper corn                     ',
          '10-12 pieces chicken (with bone)             ',
          '1 tsp ajinomoto (optional)                   ',
          'to taste salt                                ',
          '2 tsp white pepper                           ',
          'oil for frying                               ',
          '1 tbsp black vinegar                         ',
          '2 tsp chilli oil                             ',
        ],
        steps: [
          'Flash fry the chicken with ginger till there colour changes to golden.                                    ',
          'Now, drain the oil and keep this aside.                                                               ',
          'Now, add garlic, spring onions green pepper corns and the brown peppercorn.                           ',
          'Stir for 5 minutes and then add the dry chillies, white pepper powder, ajino moto, salt and chilli oil.   ',
          'Stir again for 5-10 minutes and add the black vinegar.                                                    ',
          'Stir fry for 10 minutes and garnish with green peppercorns.                                               ',
          'Szechwan chilli chicken is ready to be served.                                                            ',
        ]),
    ChinaFood(
        id: 'r1',
        title: ' Spring Rolls',
        country: 'China',
        imageUrl:
            'https://i.ndtvimg.com/i/2015-02/spring-roll_625x350_51424323845.jpg',
        codeFood: 3,
        information:
            'A crisp appetizer where shredded veggies are encased in thin sheets and then fried golden. Little munchies to prepare at home for a high tea menu or just a party starter, serve with a tangy dip.',
        duration: ' 40 min',
        ingredients: [
          'For the pancakes:                                     ',
          '1/2 cup flour                                         ',
          '1 egg                                                 ',
          '1/4 tsp salt                                          ',
          '1/4 cup water                                         ',
          '1/4 cup milk                                          ',
          '3 Tbsp oil mix the water, oil and milk together       ',
          'For the filling:                                      ',
          '1 cup thinly shredded cabbage                         ',
          '1 cups spring onions-including leaves, finely chopped ',
          '1 cup thinly shredded carrot                          ',
          '1/2 tsp salt                                          ',
          '2 Tbsp oil                                            ',
          '4 cloves garlic-very finely chopped                   ',
          '1 tsp soya sauce                                      ',
          '2 Tbsp celery-chopped fine                            ',
          '1 Tbsp flour, made into thin paste by adding water    ',
          'Oil for deep frying                                   ',
        ],
        steps: [
          'Make the pancakes with the pancake ingredients.                                                                                                      ',
          'Heat the 1 tbsp oil and stir-fry the garlic and onions over high heat till the onions are a little soft.                                             ',
          'Add the rest of the filling ingredients and turn around a few times, still over a high heat.                                                         ',
          'Take a pancake and place a heaped tbsp of filling towards one edge.                                                                                  ',
          'Fold that edge over the filling, then the two sides thus formed over the fold, and roll over till the end, sealing that edge with the flour paste.   ',
          'It is very important to seal the filling in, so that it does not spill out while frying. Double fry the pancakes.                                    ',
        ]),
    ChinaFood(
        id: 'r1',
        title: 'Stir Fried Tofu',
        country: 'China',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-06/tofu-with-rice_625x350_81466070125.jpg',
        codeFood: 5,
        information:
            'A simple stir-fry with tofu and oriental sauces. Sti fried togu with rice is a great main course dish to prepare at home laced with flavourful spices and sauces. Serve with some fried rice to make a wholesome meal.',
        duration: '40 min',
        ingredients: [
          'For the tofu:                         ',
          '100 gms tofu                          ',
          '2 tsp chilly paste                    ',
          '1 Lemon grass stick                   ',
          '2 Shallots , chopped                  ',
          '1 inch ginger , chopped               ',
          '2 tsp soya sauce                      ',
          '3 Garlic cloves, chopped              ',
          '1 inch red onion , chopped            ',
          '2 tsp honey                           ',
          'Handful of coriander leaves, chopped  ',
          '1 tsp refined oil                     ',
          'For the fried rice:                   ',
          'Carrots, chopped                      ',
          'Spring onions, chopped                ',
          'To flavor salt & pepper               ',
          '1 Fresh red chilly, chopped           ',
          '1 Ginger, chopped                     ',
          '2 tsp soya sauce                      ',
          '1/2 Lemon (squeezed)                  ',
          'Handful Handful of coriander , chopped',
          '1 tsp olive oil                       ',
        ],
        steps: [
          'Drizzle refined oil in a preheated pan and add chopped mariner and stir well.                    ',
          'Then add ginger, garlic, shallots and salt & pepper.                                             ',
          'Add red chilly paste, soya sauce and honey.                                                      ',
          'Add some coriander leaves and mix it all together.                                               ',
          'For the fried rice:                                                                              ',
          'Drizzle olive oil in a pre-heated pan and add carrots, spring onions, ginger and salt & pepper.  ',
          'Then add fresh red chilly, lemon juice and soya sauce and stir all together.                     ',
          'Add some chopped coriander leaves.                                                               ',
          'Cook it away for 5-7 minutes.                                                                    ',
          'Serve it on a platter.                                                                           ',
        ]),
    ChinaFood(
        id: 'r1',
        title: 'Chicken with Chestnuts',
        country: 'China',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-06/dhaniwal-chicken_625x350_71464783643.jpg',
        codeFood: 4,
        information:
            'Stir-fried mushrooms with minced chicken, water chestnut and radish along with a host of veggies and sauces like date puree, fish sauce and the Chinese classic soya sauce. This earthy recipe is perfect for a holiday feast.',
        duration: '45 min',
        ingredients: [
          '5 dried Chinese mushrooms   ',
          '2 Tbsp sesame oil           ',
          '1/2 kg chicken mince        ',
          '1 diced green capsicum      ',
          '1 diced red capsicum        ',
          '1 Tbsp chopped garlic       ',
          '1 Tbsp shredded ginger      ',
          '3 Tbsp white radish         ',
          '12-14 peeled water chestnuts',
          '2 Tbsp chopped spring onion ',
          '1 Tbsp soya sauce           ',
          '1 Tbsp fish sauce           ',
          '1 Tbsp date puree           ',
          '1 Tbsp vinegar              ',
          '50 ml water                 ',
          '1/2 tsp chilli flakes       ',
          '1 ice-berg lettuce          ',
          '1 Tbsp chopped coriander    ',
        ],
        steps: [
          'Soak mushrooms in boiling water for 30 minutes. Drain and discard stems.       ',
          'Heat oil. Stir-fry chicken until browned. Remove from pan.                     ',
          'Stir-fry capsicum, ginger and garlic for two minutes.                          ',
          'Return chicken to pan with remaining ingredients, except lettuce and coriander.',
          'Heat through and season well.                                                  ',
          'Serve on a bed of lettuce, garnished with coriander                            ',
        ]),
    ChinaFood(
        id: 'r1',
        title: 'Honey Chilli Potato',
        country: 'China',
        imageUrl:
            'https://i.ndtvimg.com/i/2018-01/honey-chilli-potato_620x330_81514872067.jpg',
        codeFood: 5,
        information:
            'The quintessential Indo-Chinese snack! Honey chilli potato is what you\'ll find at every Chinese van in and around north India. It has the perfect balance of sweet and spicy with sliced potatoes tossed with a host of sauces and spices.',
        duration: '35 min',
        ingredients: [
          'For Frying Potatoes:              ',
          '2 Nos Potatoes, sliced            ',
          '5 Tbsp Corn flour                 ',
          '1 1/2 Tbsp Salt                   ',
          '2 tsp Chilli Powder               ',
          'For Honey Chilli Sauce:           ',
          '1 1/2 tsp Garlic                  ',
          '1 tsp Ginger                      ',
          '2 Nos Whole Red Chillies , chopped',
          '1 tsp Chilli Flakes               ',
          '2 tsp Tomato Sauce                ',
          '2 tsp Chilli Sauce                ',
          '1 tsp Vinegar                     ',
          '2 Tbsp Honey                      ',
          '1 tsp Salt                        ',
          '4 tsp Sesame Seeds , roasted      ',
          '2 Bulbs Spring Onions             ',
        ],
        steps: [
          'Take two potatoes and cut them into slices in a bowl.Honey Chilli Potato                                              ',
          'In the bowl add corn flour, salt and red chilli powder.Honey Chilli Potato                                             ',
          'Toss them well so that the mixture coats the sliced potatoes properly.                                                 ',
          'Now heat oil in a broad pan and deep fry the potatoes on medium flame till golden brown and crisp.Honey Chilli Potato  ',
          'Do not fry on high flame otherwise they will burn from outside and remain uncooked from inside.                        ',
          'In another pan dry roast the sesame seeds on low heat till light brown and keep aside.Honey Chilli Potato              ',
          'r Preparing Honey Chilli Sauce:                                                                                        ',
          'Heat oil and add garlic, ginger, whole red chillies, chilli flakes and tomato sauce. Stir well.Honey Chilli Potato     ',
          'Now add chilli sauce, vinegar, honey and salt. Mix all the ingredients well to make a sauce.Honey Chilli Potato        ',
          'Add the fried potatoes and coat them well with the sauce.                                                              ',
          'Toss well and sprinkle the roasted sesame seeds and spring onions.Honey Chilli Potato                                  ',
          'Combine the ingredients well and serve the crunchy honey chilli potatoes immediately.Honey Chilli Potato               ',
        ]),
  ];

  List<ChinaFood> get chinaRecipes {
    return [..._chinaRecipes];
  }
}
