import 'package:flutter/material.dart';

class FranceFood with ChangeNotifier {
  final String id;
  final String title;
  final String country;
  final String imageUrl;
  final double codeFood;

  final List<String> ingredients;
  final List<String> steps;
  final String duration;
  final String information;

  FranceFood({
    @required this.id,
    @required this.title,
    @required this.country,
    @required this.imageUrl,
    @required this.codeFood,
    @required this.ingredients,
    @required this.steps,
    @required this.duration,
    @required this.information,
  });
}

class France with ChangeNotifier {
  List<FranceFood> _franceRecipes = [
    FranceFood(
        id: 'r1',
        title: 'onion soup',
        country: 'France',
        imageUrl:
            'https://www.expatica.com/app/uploads/media/upload/714571.jpg',
        codeFood: 4,
        information:
            'This is a traditional French soup made of onions and beef stock,'
            ' usually served with croutons and melted cheese on top. The soup’s origin can be traced as far back as the Romans – it'
            ' was typically a poor dish – although the current version dates from the 18th century. The remarkable taste in French onion soup '
            'is from the caramelisation of the onions, to which sometimes brandy or sherry is added at the end of the slow-cooking process. '
            'The liquid is typically meat stock, although variations include using just water, adding milk or thickening it with eggs or flour.',
        duration: '1 h 20 min',
        ingredients: [
          '6 large lamb leg chops',
          '50g butter',
          '3 brown onions, halved, thinly sliced',
          '2 garlic cloves, crushed',
          '1L (4 cups) Massel beef style liquid stock',
          '3 sprigs fresh thyme',
          '2 dried or fresh bay leaves',
          '8 x 1cm-thick slices baguette (French breadstick)',
          '4 slices Swiss cheese',
          'Fresh thyme leaves, to serve',
        ],
        steps: [
          'Place the lamb in a large saucepan and cover with cold water.',
          ' Bring to the boil over medium heat. Reduce heat to medium-low and simmer for 1 hour or until tender.',
          'Transfer the lamb to a clean work surface. Discard the cooking liquid. ',
          'Remove the bones from the lamb and discard. Finely shred. Set aside to cool.',
          'Meanwhile, melt the butter in the pan over medium-low heat. ',
          'Add the onion and garlic and cook, stirring often, for 15 minutes or until soft and caramelised. Season with salt and pepper.',
          'Add stock, thyme and bay leaves. Bring to a simmer and cook for 30 minutes.',
          'Discard the thyme and bay leaves.',
          ' Transfer the mixture to the bowl of a food processor and process until smooth.',
          ' Return to the pan. Stir in the lamb. Stir over low heat until heated through.',
          'Preheat grill on medium. Place the bread slices on a baking tray. ',
          'Cook under grill for 2-3 minutes each side or until toasted.',
          ' Cut the cheese slices in half and divide among the bread slices.',
          ' Cook under grill for 2-3 minutes or until the cheese melts.',
          'Divide soup among serving bowls. Top each soup with 2 cheese toasts and thyme. Serve.',
        ]),
    FranceFood(
        id: 'r1',
        title: 'Coq au vin',
        country: 'France',
        imageUrl:
            'https://www.expatica.com/app/uploads/media/upload/714572.jpg',
        codeFood: 5,
        information:
            'This quintessential French food was popularised by Julia Child through her television show and book and seen as one of her signature dishes. It is a dish of chicken braised with wine, mushrooms, salty pork or bacon (lardons), mushrooms, onions, often garlic and sometimes with a drop of brandy. Although the name translates as ‘rooster or cock in wine’ – and braising is ideal for tougher birds – the recipe usually uses chicken or capon. A red Burgundy wine is typically used, although French regional variations exist using local wines',
        duration: '1 h 30 min',
        ingredients: [
          '2 tablespoons olive oil, divided',
          '100g streaky bacon (about 4 rashers), diced',
          '8 chicken drumsticks, skin removed from each in 1 piece and reserved',
          'Plain flour, for dusting',
          '400g brown cup mushrooms, halved',
          '8 small shallots, peeled',
          '8 cloves garlic, peeled',
          '6 sprigs thyme',
          '2 cups white Burgundy wine or chardonnay',
          '1 cup chicken stock',
          '1/4 cup chopped fresh flat-leaf parsley',
        ],
        steps: [
          'To make the coq au vin: Heat a large heavy pot over medium-high heat.',
          ' Add 1 tablespoon of the oil and the bacon. ',
          'Cook, stirring, for about 4 minutes, or until the bacon is crisp. ',
          'Using a slotted spoon, remove the bacon and set aside.',
          ' Season the chicken drumsticks with salt and pepper and dust with flour, shaking off any excess.',
          ' Add the chicken to the pot and cook, turning as needed, for about 8 minutes, or until the chicken is browned all over.',
          ' Remove the chicken from the pot and set it aside. ',
          'If the pot is dry, add the remaining 1 tablespoon oil to the bacon fat and add the mushrooms, shallots, garlic and thyme.',
          ' Cook, stirring and scraping the brown bits from the bottom of the pot, ',
          'for about 4 minutes, or until the vegetables have caramelised.',
          ' Add the wine, bring to a boil and cook for about 2 minutes, or until the wine has reduced slightly. ',
          'Add the stock, chicken and bacon and bring to a simmer and cook partially covered for 40 minutes.',
          ' Remove the lid and cook 20 minutes, or until the chicken is tender and the sauce is thick.',
          'Meanwhile, to make the chicken skin crisp: Preheat the oven to 220C (200C fan-forced).',
          'Place a sheet of baking paper on a large overturned baking tray. ',
          'Cut the chicken skins in half and lay them, fatty side down, and in a single layer on the prepared baking tray and season with salt.',
          ' Place another sheet of baking paper on top of the skins and place a heavy baking tray on top to weigh down the skins.',
          'Bake in the oven for about 20 minutes, or until the fat has rendered and the skins are golden brown and crisp.',
          ' Transfer the skins to a rack to cool. Break into bite-size pieces.',
          'To serve: Divide the chicken drumsticks among 4 plates or shallow bowls.',
          ' Stir the parsley into the cooking liquid and season to taste with salt and pepper.',
          ' Divide the sauce and vegetables among the plates. Garnish each plate with the crispy chicken skin and serve.',
        ]),
    FranceFood(
        id: 'r1',
        title: 'Cassoulet',
        country: 'France',
        imageUrl:
            'https://img.taste.com.au/YXM0EK3n/w643-h428-cfill-q90/taste/2016/11/sausage-cassoulet-92282-1.jpeg',
        codeFood: 3,
        information:
            'Cassoulet is a comfort dish of white beans stewed slowly with meat, typically pork or duck but also sausages, goose, mutton or whatever else the chef has around. This peasant dish originates from southern France and is popular in Toulouse, Carcassonne and Castelnaudary. The name of the dish comes from the pot (cassole) it’s traditionally baked in, which is typically shaped like an inverted cone to give a crust shape. This is a rich, hearty meal perfect for colder months.',
        duration: '30 min',
        ingredients: [
          '1 kg Outback Spirit pork kakadu plum sausages',
          '1 tablespoon Coles Brand pure olive oil',
          '1 onion, chopped',
          '175g Coles Brand short cut bacon, chopped',
          '690g Coles Brand Italian passata',
          '1/2 cup basil leaves, plus extra leaves to serve',
          '400g can Coles Brand butter beans, rinsed, drained',
          '250g broccoli florets, steamed, to serve',
        ],
        steps: [
          'Heat a frying pan on medium. Cook sausages for 4-5 mins, turning once, until browned all over.',
          ' Removed from pan. Wipe pan clean with a paper towel.',
          'Heat oil in same pan on medium. Cook onion for 5 mins, or until soft. Add bacon and cook for 3-4 mins, or until bacon is brown. Add tomato passata, basil and 1/2 cup water. Season. Simmer for 5 mins, or until thickened slightly. Add beans and stir to combine.',
          'Thickly slice sausages. Add to tomato sauce and simmer for 2-3 mins, or until cooked through. Scatter over extra basil. Serve with broccoli',
        ]),
    FranceFood(
        id: 'r1',
        title: 'Beef bourguignon',
        country: 'France',
        imageUrl:
            'https://img.taste.com.au/3lj9q_AD/w643-h428-cfill-q90/taste/2016/11/beef-bourguignon-75573-1.jpeg',
        codeFood: 4,
        information:
            'Boeuf bourguignon is a traditional French meal that has become internationally well-known. Coming from the same region as coq au vin – Burgundy (or in French, Bourgogne) in eastern France – beef bourguignon has several similarities. The dish is a stew made of beef braised in red wine, beef broth and seasoned with garlic, pearl onions, fresh herbs and mushrooms. This recipe is just one example of how traditional peasant dishes have been adopted into haute cuisine; the method of slowly simmering beef in wine was likely developed to tenderise tough (or cheap) cuts of meat. Traditional preparation time is two days to tenderise the meat and intensify the flavours. In Burgundy in late August, the Fête du Charolais (in French) celebrates the prized Charolais beef with music, meat and bœuf bourguignon',
        duration: '2 h 35 min',
        ingredients: [
          '2 1/2 tablespoons olive oil',
          '1.5kg beef chuck steak, trimmed, cut into 5cm pieces',
          '1 large brown onion, finely chopped',
          '200g shortcut rindless bacon, halved lengthways, cut into 1cm strips',
          '2 garlic cloves, finely chopped',
          '1 cup red wine',
          '1/2 cup Massel beef stock',
          '1 tablespoon tomato paste',
          '16 small pickling onions, peeled ',
          '400g small button mushrooms',
          'Green beans, to serve',
          'Mashed potato, to serve',
          'Salt, to season',
        ],
        steps: [
          'Heat 2 tablespoons oil in a large, heavy-based casserole dish over medium-high heat. ',
          'Cook beef, in batches, for 5 to 6 minutes or until browned. Transfer to a bowl.',
          'Reduce heat to medium. Heat remaining oil in dish. Add brown onion and bacon. ',
          'Cook, stirring, for 6 minutes or until onion has softened. Add garlic. Cook for 1 minute.',
          'Return beef and juices to pan. Add wine. Bring to the boil.',
          ' Add stock and tomato paste. Bring to the boil. Reduce heat to low. Simmer, covered, for 1 hour and 15 minutes.',
          ' Add pickling onions and mushrooms. Cook, covered, for 30 minutes or until meat and onions are tender. Season with salt and pepper. Serve.',
        ]),
    FranceFood(
        id: 'r1',
        title: 'Chocolate soufflé',
        country: 'France',
        imageUrl:
            'https://www.expatica.com/app/uploads/media/upload/714574.jpg',
        codeFood: 5,
        information:
            'The word soufflé derives from the French verb to ‘blow out’ and is an airy, egg-baked dish with origins dating back to early 18th-century France. Soufflé is eaten savoury or sweet in France, and you’ve likely found chocolate soufflé on dessert menus worldwide. The crispy chocolate crust with an oozing, creamy chocolate centre gives this dessert a sweet surprise.',
        duration: ' 40 min',
        ingredients: [
          'Melted butter, to grease',
          '4 1/2 tablespoons caster sugar',
          '60g butter',
          '2 tablespoons plain flour',
          '160ml (2/3 cup) milk',
          '210g good-quality dark chocolate, chopped',
          '3 eggs, separated',
          '125ml (1/2 cup) thin cream',
          '2 tablespoons brown sugar',
          '1 teaspoon vanilla essence',
          'Icing sugar, to dust',
        ],
        steps: [
          'Preheat oven to 180°C. ',
          'Brush six 160ml (2/3-cup) ovenproof souffle dishes with melted butter to grease (using upward strokes on side).',
          ' Sprinkle the inside with 1 1/2 tablespoons of caster sugar, shake out any excess.',
          'Melt 30g of the butter in a saucepan over medium heat.',
          ' Add flour and use a wooden spoon to stir for 1 minute or until mixture is smooth and begins to bubble. ',
          'Remove from heat, gradually add milk, stirring until smooth and combined. Return to medium heat, ',
          'stir until mixture thickens and comes to the boil. Boil for 1 minute, stirring. Remove from heat.',
          'Stir in 125g of the chocolate and remaining caster sugar until combined.',
          ' Transfer to a bowl. Add egg yolks and stir until well combined.',
          'Use an electric beater to whisk egg whites in a clean, dry bowl until firm peaks form.',
          ' Use a metal spoon to fold one-third of the egg whites into chocolate mixture. ',
          'Fold in remaining egg whites until just combined.',
          'Spoon the mixture evenly into prepared dishes. Place on a baking tray. Bake in preheated oven for 15-20 minutes or until well risen.',
          'Meanwhile: combine remaining chocolate, remaining butter, brown sugar, cream and vanilla essence in a saucepan over low heat.',
          ' Cook, stirring, for 2 minutes or until chocolate melts and mixture is well combined. Simmer, uncovered, for 1 minute. ',
          'Remove from heat. Place in a jug.',
          'To serve, place ramekins on plates. Dust with icing sugar.',
          ' Use a spoon to make a hole in top of each souffle, pour in a little chocolate sauce.',
        ]),
    FranceFood(
        id: 'r1',
        title: 'Tarte flamiche',
        country: 'France',
        imageUrl:
            'https://img.taste.com.au/UpQGz6sJ/w643-h428-cfill-q90/taste/2016/11/tarte-flamiche-with-paprika-thyme-pastry-85721-1.jpeg',
        codeFood: 4,
        information:
            'Flamiche means ‘cake’ in Flemish and this dish originates from northern France, near the border with Belgium. It has a puff-pastry crust filled with cheese and vegetables and resembles a quiche. The traditional French filling is with leeks and cream. There is also a pizza-like version of flamiche, which is without the top crust of the pie. For a southern French twist, try the thin crusty pissaladière which is topped with anchovies, onions and olives.',
        duration: '2 h 30 min',
        ingredients: [
          '50g unsalted butter',
          '1 tablespoon olive oil',
          '3 large onions, thinly sliced',
          '150g bacon, chopped',
          '4 eggs',
          '100ml thickened cream',
          '1 1/4 cups (150g) gruyere, grated',
          'Micro herbs, to garnish',
          'PAPRIKA THYME PASTRY',
          '200g plain flour',
          '1/2 teaspoon paprika',
          '1/2 teaspoon dried thyme leaves',
          '100g chilled unsalted butter, chopped',
          '1 egg yolk',
        ],
        steps: [
          'For the pastry, place the flour, paprika, thyme and butter in the bowl of a food processor with 1/2 teaspoon salt and whiz until the mixture resembles fine breadcrumbs. ',
          'Add egg yolk and 2 tablespoons chilled water. ',
          'Process until the mixture comes together in a smooth ball, then enclose in plastic wrap and chill for 30 minutes',
          'Meanwhile, melt butter and oil in a frypan over medium-low heat.',
          ' Add onion and 1/2 teaspoon salt and cook for 20 minutes, stirring occasionally, until softened.',
          ' Add bacon and cook for a further 3-4 minutes until the onion is tinged golden and the bacon is almost cooked.',
          ' Remove from heat and set aside to cool.',
          'Preheat the oven to 180°C. Grease a 24cm loose-bottom tart pan.',
          ' Roll out the pastry on a lightly floured surface, then use it to line the base and sides of the tart pan. ',
          'Line with baking paper and fill with uncooked rice or baking weights. ',
          'Cook for 10 minutes, then remove paper and baking weights and return to the oven and cook for a further 5 minutes or until the pastry is cooked and dry.',
          'Beat eggs, cream and 100g cheese together and season. ',
          'Spread the onion mixture in the tart shell, then pour over the egg mixture. ',
          'Sprinkle with remaining 50g cheese and bake for 25 minutes or until filling is golden and set.',
          ' Garnish with micro herbs, to serve.',
        ]),
    FranceFood(
        id: 'r1',
        title: 'French duck confit',
        country: 'France',
        imageUrl:
            'https://img.taste.com.au/jXwhvMiD/w643-h428-cfill-q90/taste/2016/11/french-duck-confit-with-french-dressing-84044-1.jpeg',
        codeFood: 3,
        information:
            'Confit de canard is a tasty French dish of duck – although goose and pork can also be used – and is considered one of the finest French dishes. The meat is specially prepared using a centuries-old preserve and slow-cooking process (confit), where the duck meat is marinated in salt, garlic and thyme for up to 36 hours and then slow-cooked in its own fat at low temperatures (an alternative to deep-frying). It is typically served with confit roasted potatoes and garlic on the side. Today this French dish is served all over France, although it is considered a specialty of the Gascony region.',
        duration: '1 h 10 min',
        ingredients: [
          '1kg desiree potatoes, peeled, chopped into 2cm pieces',
          '4 confit duck legs ',
          '4 eschalots, finely chopped',
          '200ml white wine',
          '1 cup (250ml) Massel chicken style liquid stock',
          '1 tablespoon Dijon mustard',
          '1 tablespoon finely chopped flat-leaf parsley',
          '1 tablespoon fresh tarragon leaves , finely chopped',
          '6 tomatoes, quartered, seeds removed',
          '400g baby green beans, blanched, refreshed',
        ],
        steps: [
          'Preheat oven to 200°C. Line a baking tray with baking paper. ',
          'Place potatoes in a pan of cold, salted water and bring to the boil over medium-high heat.',
          ' Cook for 8-10 minutes until just tender. Drain well.',
          'Scrape off excess fat from duck and set aside. ',
          'Place 2 tablespoons duck fat in a baking dish and melt in the oven for 2 minutes.',
          ' Toss potatoes in fat and season. Roast potatoes for 10 minutes. ',
          'Place duck on lined tray and roast with the potatoes for a further 20 minutes, turning potatoes once, until duck and potatoes are crisp and golden.',
          'Meanwhile, heat 1 tablespoon reserved fat in a pan over a medium heat.',
          ' Cook eschalot, stirring, for 1 minute until just starting to soften.',
          ' Add wine and increase heat to high. Simmer for 8-10 minutes until reduced to about 2 tablespoons.',
          ' Add stock and simmer for a further 6-8 minutes until reduced by half. Whisk in mustard and herbs, then season.',
          'Cut tomatoes into strips, then toss with beans and half the dressing. Serve with potatoes, duck and remaining dressing.',
        ]),
    FranceFood(
        id: 'r1',
        title: 'Nicoise salad',
        country: 'France',
        imageUrl:
            'https://img.taste.com.au/AX19e7N2/w643-h428-cfill-q90/taste/2016/11/nicoise-style-tuna-salad-91762-1.jpeg',
        codeFood: 5,
        information:
            'Salade niçoise is a typical French salad from the Provence region, which can be served as a side dish or a light meal on its own. It’s typically a combination of lettuce, fresh tomatoes, boiled eggs, (canned or fresh) tuna, green beans, Nicoise Cailletier olives and anchovies, although many variations exist.',
        duration: '30 min',
        ingredients: [
          '400g baby potatoes, quartered',
          '200g green beans, trimmed, halved',
          '4 Coles Brand free range eggs',
          '425g can Coles Brand tuna chunks in springwater, drained',
          '2 truss tomatoes, cut into wedges',
          '120g Coles Brand 4 leaf salad mix',
          '100g pitted kalamata olives, drained',
          '100g feta, from the deli, crumbled',
          '1/4 cup Coles Simply Less balsamic dressing',
        ],
        steps: [
          'Cook the potatoes in a large saucepan of boiling water for 10 minutes or until just tender, ',
          'adding the beans for the last 2-3 minutes of cooking. Rinse the potatoes and beans under cold water. Drain and cool.',
          'Meanwhile, bring the eggs to the boil in a saucepan of water over high heat.',
          ' Reduce heat to medium and gently simmer for 6-7 minutes. ',
          'Cool under cold water. Drain. Peel and cut into quarters.',
          'Combine the potato, beans, hard-boiled egg, tuna, tomato, salad leaves, olives and feta in a large bowl. ',
          'Season and drizzle with the dressing.',
        ]),
    FranceFood(
        id: 'r1',
        title: 'Ratatouille',
        country: 'France',
        imageUrl:
            'https://www.expatica.com/app/uploads/media/upload/714583.jpg',
        codeFood: 4,
        information:
            'Ratatouille is another internationally recognised French dish, hailing from the southeastern French region of Provence. It is a stewed vegetable recipe that can be served as a side dish, meal or stuffing for other dishes, such as crepes and omelettes. The vegetables are generally first cooked in a shallow pan on a high heat with a small amount of fat, and then oven-baked in a dish. French chefs continually debate the correct way to cook ratatouille: some do not agree with sauteing all the vegetables together, such as Julia Child, and argue that the vegetables should be cooked separately and layered into a baking dish. The ingredients consist of tomatoes, garlic, onions, zucchini, eggplant, carrots, bell peppers, basil, marjoram, thyme and other green herbs. A similar dish popular in the French Basque country is piperade, which typically adds ham and sometimes eggs to the stewed vegetable mix.',
        duration: '1 h 35 min',
        ingredients: [
          '250ml (1 cup) Massel vegetable liquid stock',
          '2 red onions, chopped',
          '2 garlic cloves, crushed',
          '3 medium (about 660g) red capsicums, deseeded, cut into 2cm pieces',
          '2 medium (about 440g) green capsicums, deseeded, cut into 2cm pieces',
          '2 medium (about 700g) eggplant, cut into 3cm pieces',
          '3 400g cans Italian whole peeled tomatoes (La Gina brand)',
          '70g (1/4 cup) tomato paste',
          '2 teaspoons caster sugar',
          '4 (about 320g) zucchini, quartered, cut into 2cm pieces',
          '1 cup roughly chopped fresh basil leaves',
          'Salt & freshly ground black pepper',
        ],
        steps: [
          'Bring the stock to the boil in a large saucepan over high heat.',
          ' Reduce heat to medium, add onions and garlic, and cook, stirring, for 2 minutes or until the onions soften slightly.',
          'Add capsicums and eggplant, and cook, stirring, for 2 minutes. Stir in the tomatoes, tomato paste and sugar.',
          ' Cover and cook over low heat for 40 minutes.',
          'Stir in zucchini. Cook, covered, for 20 minutes or until vegetables are soft.',
          ' Remove from heat. Stir in basil. Taste and season with salt and pepper.',
        ]),
    FranceFood(
        id: 'r1',
        title: 'Tarte tatin',
        country: 'France',
        imageUrl:
            'https://www.expatica.com/app/uploads/media/upload/714581.jpg',
        codeFood: 3,
        information:
            'They say this French apple tarte was made by mistake in 1898 by Stephanie Tartin when trying to make a traditional apple pie. When she accidentally left the apples in sugar and butter too for long in the pan, in a hurry to rescue the dessert she put the pastry base on top of the burning fruit and placed the pan in the oven. She supposedly served the upside-down tart to her guests at Hôtel Tatin and the result turned into the hotel’s signature dish. Although the tarte’s origin is disputed, the delicious result is not.',
        duration: '55 min',
        ingredients: [
          ' 150g (1 cup) plain flour',
          '1/2 teaspoon baking powder',
          '40g reduced-fat dairy spread',
          '1 1/2 tablespoons caster sugar',
          '1 tablespoon water',
          ' 1 egg white, lightly whisked',
          'Melted butter, to grease',
          '70g (1/3 cup, firmly packed) brown sugar',
          '1 teaspoon ground cinnamon',
          '4 Granny Smith apples, peeled, cored, cut into thin wedges',
          'Plain flour, extra, to dust',
        ],
        steps: [
          'Combine flour and baking powder in a bowl.',
          ' Use your fingertips to rub dairy spread into the flour mixture until it resembles fine breadcrumbs.',
          ' Stir in caster sugar. Make a well in the centre and add the water and egg white. ',
          'Use a round-bladed knife in a cutting motion to mix until evenly incorporated and the mixture begins to hold together.',
          ' Use your hands to press the dough into a disc. ',
          'Cover with plastic wrap and place in the fridge for 30 minutes to rest.',
          'Preheat oven to 200°C. Brush a round 20cm (base measurement) cake pan with melted butter to lightly grease.',
          ' Line the base with non-stick baking paper. Sprinkle the base evenly with brown sugar and cinnamon.',
          'Heat a large non-stick frying pan over high heat.',
          ' Add one-third of the apple and cook, turning occasionally, for 2 minutes or until golden. ',
          'Transfer to a plate. Repeat, in 2 more batches, with the remaining apple.',
          ' Arrange the apple over the sugar mixture in the base of the pan.',
          'Roll out the pastry on a lightly floured surface to a 20cm-diameter disc. ',
          'Place pastry disc over apple and gently press to cover. ',
          'Bake in oven for 30-35 minutes or until pastry is golden. Remove from oven.',
          ' Set aside for 5 minutes before turning onto a serving platter. Serve immediately.',
        ]),
  ];

  List<FranceFood> get franceRecipes {
    return [..._franceRecipes];
  }
}
