import 'package:flutter/material.dart';

class IndiaFood with ChangeNotifier {
  final String id;
  final String title;
  final String country;
  final String imageUrl;
  final double codeFood;
  final List<String> ingredients;
  final List<String> steps;
  final String duration;
  final String information;

  IndiaFood({
    @required this.id,
    @required this.title,
    @required this.country,
    @required this.imageUrl,
    @required this.codeFood,
    @required this.ingredients,
    @required this.steps,
    @required this.duration,
    @required this.information,
  });
}

class India with ChangeNotifier {
  List<IndiaFood> _indiaRecipes = [
    IndiaFood(
        id: 'r1',
        title: 'Rogan Josh',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2015-03/mutton-korma_625x350_51426244304.jpg',
        codeFood: 4,
        information:
            'It is one of the signature dishes of Kashmir. Robust with varied spices, the dish is cooked with the aroma of fennel seeds, garam masala, bay leaves, turmeric and is indeed a celebration of all senses. A delicious dinner party option, Rgan Josh can be best paired with butter naan or paratha.',
        duration: '2 h 30 min',
        ingredients: [
          '4 Coles Australian Lamb Shanks, French trimmed',
          '2 brown onions, cut into wedges',
          '1/2 cup (125g) rogan josh curry paste',
          '500g Greek-style yoghurt',
          '300g green beans, ends trimmed',
        ],
        steps: [
          ' Heat a large non-stick casserole pan over medium-high heat.',
          ' Cook the lamb, in 2 batches, turning occasionally, for 5 mins or until brown all over.',
          ' Transfer to a bowl. Reduce heat to low. ',
          'Add onion to the pan and cook for 5 mins or until onion softens.',
          'Return the lamb to the pan with the yoghurt and 2 cups (500ml) water.',
          ' Cook, covered, turning occasionally, for 2 hours or until lamb is falling off the bone.',
          'Add the beans to the curry and cook for 5 mins or until bright green and tender crisp. Season.',
        ]),
    IndiaFood(
        id: 'r1',
        title: 'Butter Chicken',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2015-01/butter-chicken_625x350_71421325695.jpg',
        codeFood: 5,
        information:
            'This gorgeous plate is the reason every Punjabi takes pride in his food. Chunks of chicken marinated overnight in yogurt and a beautiful mix of spices, served with a dollop of melting cream or butter on top. A perfect dinner party recipe, this North-Indian style chicken recipe is made throughout the country with equal zest.',
        duration: ' 30 min',
        ingredients: [
          '700g small gold sweet potatoes, cut into 1.5cm-thick slices',
          '600g Coles RSPCA Approved Australian Chicken Thigh Fillets',
          '485g jar Coles Butter Chicken Simmer Sauce',
          '400ml can coconut milk',
          '1 lime, juiced',
          '1 tbs fish sauce',
          '6 stems curry leaves',
          '20g unsalted butter',
          '1 brown onion, thinly sliced',
          '1 cup (200g) basmati ',
          'Steamed snow peas, to serve',
          '1 long green chilli, thinly sliced (optional)',
          'Coriander leaves, to serve',
        ],
        steps: [
          'Preheat oven to 200°C.',
          ' Place the sweet potato in a large microwave-safe bowl.',
          'Cover and cook in microwave on high for 6 mins or until just tender.',
          'Place the chicken, simmer sauce, coconut milk, lime juice and fish sauce in a large flameproof roasting pan. ',
          'Bring to the boil over high heat.',
          ' Top with the sweet potato.',
          ' Bake for 20 mins or until the chicken is cooked through,',
          ' adding 4 curry leaf stems in the last 3 mins of cooking.',
          'Meanwhile, melt the butter in a saucepan over medium-high heat.',
          ' Add the onion and 2 remaining curry leaf stems and cook, stirring occasionally, for 5 mins or until the onion softens.',
          'Add the rice to the onion mixture in the pan. ',
          'Cook, stirring, for 1 min. Add 2 cups (500ml) water and stir to combine. ',
          'Bring to the boil. Reduce heat to low. Cover and cook for 12 mins or until the rice is tender and liquid is absorbed. ',
          'Set aside, covered, for 5 mins. Use a fork to separate the grains.',
          'Divide the rice and chicken among serving plates. ',
          'Serve with snow peas, chilli, if using, and coriander leaves.',
        ]),
    IndiaFood(
        id: 'r1',
        title: 'Bhapaa Aloo',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-06/bhapaa-aloo_625x350_71465281820.jpg',
        codeFood: 3,
        information:
            'A stunner of a recipe, this one gets the Bengali flavours just right. Bhapaa is the Bengali word for steamed and this bengali recipe is exactly what it means. The humble potato tossed in local flavours of panch phoron (five spice powder), coconut paste and mustard oil, steamed to perfection. You can simply say this is a vegetarian version of Bhapaa Maach, just the fish has been replaced with baby potatoes. Simple yet satisfying!',
        duration: ' 50 mins',
        ingredients: [
          '200 gm small potatoes',
          '2 tsp mustard oil',
          '1/2 tsp Bengali five spice mixture (panchphoron) (whole jeera, saunf seeds, fenugreek seeds, black mustrad seeds and kalaunji)',
          '2 dry red chillies',
          '1/2 tsp mustard paste',
          '1 tsp hung curd',
          '3/4 tsp desiccated coconut paste',
          'Pinch of green chilli paste',
          'Pinch of turmeric powder',
          'Salt - to taste',
          'Dash of lime juice',
          '2 banana leaves',
        ],
        steps: [
          'Peel the potatoes and par boil them in salted water, drain and keep aside.',
          'Heat oil in a non-stick pan, add the five spice mixture, break the red chillies in half and add them next.',
          'Stir the spices around till they splutter.',
          'Pour this over the potatoes and put aside',
          'In a mixing bowl prepare a marinade with the mustard paste, curd, coconut paste, green chilli paste and turmeric powder, whip it well.',
          'Gently mix the potatoes into this marinade.',
          'Add the salt and lime juice, mix again.',
          'Put the potatoes on a steel plate, cover with the banana leaves and steam them for 6-8 minutes. Serve hot.',
        ]),
    IndiaFood(
        id: 'r1',
        title: 'Banjari Gosht',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-03/mutton-curry_625x350_41458549653.jpg',
        codeFood: 5,
        information:
            'Experience authentic Rajasthani flavours with this exquisite blend of yogurt and juicy mutton pieces.This is an easy Indian mutton recipe that you can prepare in about an hour with our step by step process. Serve with rice or any Indian bread at a dinner party. This is also a great recipe for festival get-together during Eid or Diwali.',
        duration: '1 h ',
        ingredients: [
          '150 gm oil',
          '600 gm mutton- cleaned and cut',
          '200 gm onions',
          '50 gm whole garam masala',
          '80 gm ginger-garlic paste',
          '25 gm red chilli powder',
          'salt to taste',
          '15 gm turmeric',
          '20 gm coriander powder',
          '15 gm coriander seeds- roasted and crushed',
          '150 gm yogurt',
          '6 whole red chillies',
        ],
        steps: [
          'Heat oil, add sliced onions and saute till they turn brown.',
          'Then add ginger-garlic paste, garam masala, red chilli powder, salt, turmeric, coriander powder.',
          'Add yogurt and mutton.',
          'Add coriander seeds and allow them to cook.',
          'Garnish with pounded coriander seeds and whole red chillies.',
        ]),
    IndiaFood(
        id: 'r1',
        title: 'Chicken Stew and Appam',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-06/stew_625x350_41466057826.jpg',
        codeFood: 2,
        information:
            'This stunning dish comes straight from the hidden treasures of God\'s own country, Kerala. Chicken stew is a popular dish there as a traditional Easter dish and specially among the Christian families for breakfast or brunch. Chunks of chicken bathed in a beautifully spiced and dreamy coconut gravy with soft-centered appams, a southern-style rice pancake.',
        duration: '1 h 10 min',
        ingredients: [
          'For the chicken stew:',
          '1/2 kg Chicken',
          '4 tbsp Coconut oil',
          '2 Onions, finely chopped',
          '1 Red chilli, chopped',
          '2 Green chillies',
          '1 tbsp Ginger-garlic paste',
          '2 Tomatoes, chopped',
          '2 Potatoes (diced)',
          'Coconut milk- 1st and 2nd extract from 1 coconut',
          'Salt',
          'Pepper',
          '1 Lemon',
          '1 bunch Coriander, small',
          'For the appam:',
          '1 cup Rice, soaked',
          '3 tbsp Coconut, grated',
          '1/2 tsp Baking soda',
          '1 tbsp Rice (cooked)',
          '1/2 tsp Salt',
          '1 tbsp Sugar',
        ],
        steps: [
          'Prepare chicken stew:',
          'In a deep pan, take some coconut oil, add chopped onions, red chilli, green chilli, ginger garlic paste.',
          ' Fry until soft and golden.',
          'Add chicken to the masala mix and fry for 3 minutes.',
          'To the chicken, add tomatoes and potatoes and mix well. Add 2nd extract coconut milk.',
          'Season the chicken with pepper, salt and add water. Put the lid on and simmer for 45 minutes.',
          'To the chicken add 1st extract of coconut milk, coriander and lemon juice.',
          'epare the appam:',
          'For Appam, in a deep bowl take cooked rice, add grated coconut and soaked rice.',
          ' Blend it well into a smooth paste. Keep it overnight for fermenting.',
          'To the fermented paste, add baking soda, salt, sugar and water. ',
          'Blend the paste to a smooth, consistency.',
          'In a small kadhai, pour 1 ladle of appam mix and move the kadhai such that the mix is spread out evenly.',
          'Cover it for 1-2 minutes.',
          'Let it cook until holes appear throughout appam and the edges become brown.',
        ]),
    IndiaFood(
        id: 'r1',
        title: 'Kakori Kebab',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-03/kakori-kebabs-625_625x350_41459348085.jpg',
        codeFood: 4,
        information:
            'A famous Nawabi recipe from Lucknow passed down through generations. It derives its name from the city of Kakori on the outskirts of Lucknow. It is made with the finest meat of the lamb and a few spices. These kebabs are soft and tender, served best with coriander chutney.',
        duration: '55 min',
        ingredients: [
          '2 cups mutton/lamb (minced)               ',
          '1 tsp ginger- garlic paste                     ',
          '2 tsp salt                                     ',
          '1/4 tsp black pepper, powdered                 ',
          '2 tbsp green coriander, chopped                                ',
          'to taste green chillies, chopped                               ',
          '2 tbsp raw papaya, chopped                                     ',
          '4 Cloves                                                       ',
          '1 Black cardamom seeds                                         ',
          '1/8 tsp cinnamon, powdered                                     ',
          '1 tsp cumin seeds                                              ',
          '1 Black mace                                                   ',
          '1/4 tsp nutmeg, grated                                         ',
          '2 cups onions (browned crisp in 1/2 cup ghee), sliced          ',
          '1/4 cup bhuna chana, powdered                                  ',
          '1 Egg                                                          ',
          'Ghee for brushing some chaat masala                           ',
          'for garnishing onion rings and lemon wedges                   ',
        ],
        steps: [
          'Mix all ingredients except ghee and garnishes to marinate for about 4 hours, then grind to form a smooth, thick paste.                                                    ',
          'Knead this mixture well and mix in the roasted gram and the egg.                                                                                                          ',
          'Cover and refrigerate for another hour.                                                                                                                                   ',
          'About 25 minutes before serving, shape the meat around the skewers and place the kebabs on to a grill over a drip tray, or in a pre-heated oven (also on a drip tray).    ',
          'If cooking them over a charcoal grill, you will have to keep rotating them so that they brown and cook evenly.                                                            ',
          'They should take 15-20 minutes to cook.                                                                                                                                   ',
          'Brush with ghee and cook another 2 minutes.                                                                                                                               ',
          'Serve garnished with chaat masala onions and the lemon and serve with green chutney.                                                                                      ',
        ]),
    IndiaFood(
        id: 'r1',
        title: 'Hyderabadi Biryani ',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-01/biryani_625x350_81452497196.jpg',
        codeFood: 3,
        information:
            'It\'s the Hyderabadi Biryaniperfect choice for foodies who prefer having their rice with spice, interspersed with tender peaces of meat or chicken. Hyderabadi Biryani is a dish from down the south but spread all across the country and even abroad. Cooked in \'dum style\', it\'s layered with fried onions and mint, serve at dinner parties with a cold raita.',
        duration: '1 h 30 min',
        ingredients: [
          '1 Kg meat                                                   ',
          '1 tbsp salt                                                 ',
          '1 tbsp ginger garlic paste                                  ',
          '1 tbsp red chilli paste                                     ',
          '1 tbsp green chilli paste (sauteed brown onions to taste)   ',
          '1/2 tbsp cardamom powder                                    ',
          '3-4 Cinnamon sticks                                         ',
          '1 tbsp cumin seeds                                          ',
          '4 Cloves                                                    ',
          'A pinch of mace                                             ',
          'to taste mint leaves                                        ',
          '2 tbsp lemon juice                                          ',
          '250 gms curd                                                ',
          '4 tbsp clarified butter                                     ',
          '750 gms semi cooked rice                                    ',
          '1 tsp saffron                                               ',
          '1/2 cup water                                               ',
          '1/2 cup oil                                                 ',
          'Garnish ingredients:                                        ',
          'Eggs, boiled                                                ',
          'Carrots, sliced                                             ',
          'Cucumbers                                                   ',
        ],
        steps: [
          'Clean the meat. Now in a pan add meat, salt, ginger garlic paste, red chilli powder, green chilli paste, sauteed brown onions, cardamom powder, cinnamon, cumin seeds, cloves, mace, mint leaves and lemon juice.                          ',
          'Mix all of these ingredients thoroughly together.                                                                                                                                                                                          ',
          'Add curd, clarified butter, semi cooked rice, saffron, water and oil.',
          ' Mix it well.                                                                                                                                                       ',
          'Now apply sticky dough on the sides of the pan.                                                                                                                                                                                            ',
          'Cover with lid to seal it and cook for about 25 minutes.                                                                                                                                                                                   ',
          'Hyderabadi Biryani is ready to eat. Garnish it with boiled eggs, sliced carrots, cucumbers and serve hot.                                                                                                                                  ',
        ]),
    IndiaFood(
        id: 'r1',
        title: ' Dhokla',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-03/dhokla_625x350_41457508751.jpg',
        codeFood: 5,
        information:
            'A popular Gujarati snack, Dhokla is a steamed cake made from gram flour and channa dal is one of the best things to come out of Gujarat.  You can serve dhokla for breakfast as well as a light snack in the evening along with a cup of tea. A recipe that is steamed and made in just 30 minutes, using besan with a colorful, chili tempering is sure to set your taste buds racing!',
        duration: '40 min',
        ingredients: [
          '1 Cup gram flour (besan)                                ',
          '1 tbsp citric acid                                      ',
          '1 tbsp sugar                                            ',
          'to taste salt                                           ',
          'A pinch of turmeric                                     ',
          'Water (to make batter)                                  ',
          '1 tbsp fruit salt/ baking powder (dissolved in water)   ',
          'For the Tadka:                                          ',
          '1 tbsp oil                                              ',
          '1/2 tbsp mustard seeds                                  ',
          '1 Dried red chilli                                      ',
          '7-8 Curry leaves                                        ',
        ],
        steps: [
          'In a bowl mix gram flour, citric acid, salt, sugar and turmeric.',
          ' Add water and make it into a smooth batter with medium thick consistency.    ',
          'In a glass add the fruit salt or baking powder. Add water to it and pour this into the dhokla mixture.                                        ',
          'Grease the steaming tin with 2 drops of oil and pour the mixture into it. ',
          'Steam for about 15-20 minutes or till cooked.                       ',
          'In a pan, add oil, mustard seeds, curry leaves and red chillies. ',
          'Let it splutter.                                                             ',
          'Pour the tadka over the prepared dhokla.                                                                                                      ',
          'Cut into pieces and serve.                                                                                                                    ',
        ]),
    IndiaFood(
        id: 'r1',
        title: 'Sali Boti',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2016-06/chicken_625x350_81465813088.jpg',
        codeFood: 4,
        information:
            'This one is a an ideal example of the Parsi\'s need to mix hot and sweet. Succulent mutton chunks are cooked in tomatoes, onions, jaggery and vinegar. It reeks of bold flavours like turmeric and ginger, and is best served hot with fried potato snacks.',
        duration: '1 h 30 min',
        ingredients: [
          '1 Kg Mutton (wash and cut into very small cubes)',
          '2-3 Tbsp Ghee or oil                            ',
          '4 Tomatoes, chopped                             ',
          '4-5 Onions, finely chopped                      ',
          '3-4 Green chillies, chopped                     ',
          'Coriander leaves                                ',
          '1/2 tsp Chilli powder                           ',
          '1/2 tsp Turmeric powder                         ',
          '1 tsp Ginger-garlic paste                       ',
          '2 Cups Water                                    ',
          '1 1/2 Tbsp Vinegar                              ',
          '1 1/2 Tbsp Jaggery                              ',
          'To taste Salt                                   ',
          'For sali:                                       ',
          '6-7 Potatoes                                    ',
          'For frying Oil                                  ',
        ],
        steps: []),
    IndiaFood(
        id: 'r1',
        title: ' Idli Sambhar',
        country: 'India',
        imageUrl:
            'https://i.ndtvimg.com/i/2015-01/idli_625x350_61421915244.jpg',
        codeFood: 5,
        information:
            'This glorious steamed rice pancake with innumerable health benefits has made its way through generations. Idlis are about 2-3 inch wide, fluffy and can be relished for breakfast, lunch, snacks or dinner along with some finely ground coconut chutney and a hot steaming bowl of sambhar.',
        duration: '45 min',
        ingredients: [
          '3 cups semolina                               ',
          '2 Tbsp oil                                    ',
          '2 dry red peppers - broken into pieces        ',
          '6-7 curry leaves                              ',
          '1 tsp mustard seeds - for seasoning          ',
          'Salt to taste                             ',
          '1 cup sour yogurt                         ',
          '1 tsp eno\'s fruit salt                   ',
        ],
        steps: [
          'Heat the oil and add the peppers, curry leaves, mustard seeds and when they splutter, ',
          'add the semolina and saute over low heat, till an aroma emanates.   ',
          'Take it off the heat and let it cool.                                                                                                                     ',
          'When cool, mix the semolina and yogurt to a smooth batter add the salt.                                                                                   ',
          'Keep aside in a warm place for about an hour.                                                                                                             ',
          'Add the eno\'s and steam immediately in an idli steamer for 6-9 minutes (cocktail sized) and 15-20 minutes if the bigger size.                            ',
          'You will have to judge the time after trying a few first.                                                                                                 ',
          'Serving suggestion: Sambar and tamatar ki chutney.                                                                                                        ',
        ]),
  ];

  List<IndiaFood> get indiaRecipes {
    return [..._indiaRecipes];
  }
}
